export const TREE_DATA_UPDATED = 'TREE_DATA_UPDATED';
export const TREE_OPEN_DIR = 'TREE_OPEN_DIR';
export const TREE_CLOSE_DIR = 'TREE_CLOSE_DIR';

export const EDITOR_OPEN_FILE = 'EDITOR_OPEN_FILE';
export const EDITOR_CLOSE_FILE = 'EDITOR_CLOSE_FILE';
export const EDITOR_CHOOSE_FILE = 'EDITOR_CHOOSE_FILE';
export const EDITOR_TEXT_MODIFIED = 'EDITOR_TEXT_MODIFIED';